config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :main_fields do

    resources :creation_applications, only: [:new, :create] do
    end

    resources :fields, shallow: true do
      resources :user_assignments, shallow: true

      resources :role_applications, only: [:new, :create] do
      end

      resources :projects, shallow: true do
        resources :wikis, shallow: true

        resources :user_assignments, shallow: true
        resources :issues, shallow: true,except: [:index] do
          get 'user_issues_list', to: 'issues#user_issues_list'
          resources :user_assignments, shallow: true
          resources :user_answers, shallow: true, only: [:create, :update, :destroy]
        end
        resources :role_applications, only: [:new, :create] do
        end
      end
      

      resources :courses, shallow: true do
        resources :wikis, shallow: true
        resources :user_assignments, shallow: true
        resources :issues, shallow: true, except: [:index] do
          resources :user_assignments, shallow: true
          resources :user_answers, shallow: true, only: [:create, :update, :destroy]
        end
        resources :role_applications, only: [:new, :create] do
        end
      end

      resources :creation_applications, only: [:new, :create] do
      
      end
    end
  end

  resources :role_applications, only: [:show, :destroy] do
    patch '/accept', to: 'role_applications#accept', as: :accept
    patch '/reject', to: 'role_applications#reject', as: :reject
  end

  resources :creation_applications, only: [:show, :destroy] do
    patch '/accept', to: 'creation_applications#accept', as: :accept
    patch '/reject', to: 'creation_applications#reject', as: :reject
  end

  patch '/user_answers/:id/accept_user_answer', to: 'user_answers#accept_user_answer'
  patch '/user_answers/:id/reject_user_answer', to: 'user_answers#reject_user_answer'

  get '/notifications', to: 'notifications#index'

  resources :users
  resources :search

  post 'search/projects/', to: 'search#search_projects'

  resources :topics do
    resources :answers, only: [:create, :update, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  get '/notifications', to: 'notifications#index'

###########
  resources :advanced_abilities, only: [:create]
###########

  root to: 'main_fields#index'
end

app/models/issue.rb
class Issue < ApplicationRecord
  has_many :user_assignments, as: :assignmentable

  has_many :users, through: :user_assignments
  has_many :user_answers

  has_many :subissues, class_name: 'Issue', foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent, class_name: "Issue", foreign_key: 'parent_id', optional: true

  belongs_to :issuable, polymorphic: true, optional: true

  has_many :attachments, as: :attachable, dependent: :destroy
  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  belongs_to :author, class_name: "User", foreign_key: :author_id
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  before_action :set_issuable, only: [:new, :create, :index]

  after_action :update_project_last_issue_date, only: [:create]

  authorize_resource

  def new
    respond_with @issue = @issuable.issues.new
  end

  def show
    @user_answer = @issue.user_answers.new
    respond_with @issue
  end

  def edit; end

  def create
    @issue = @issuable.issues.create(issue_params.merge(author_id: current_user.id))
    redirect_to @issuable
  end

  def update
    @issue.update(issue_params)
    respond_with @issue
  end

  def destroy
    issuable = @issue.issuable
    @issue.destroy
    redirect_to issuable
  end

  def user_issues_list
    issue = Issue.find(params[:issue_id])
    @user_issues = UserAssignment.where(assignmentable_id: issue.id, assignmentable_type: issue.class.name)
  end


  private

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def set_issuable
    @issuable = issuable_object
  end

  def update_project_last_issue_date
    unless (defined? @issuable.last_issue_date) == nil
      @issuable.update(last_issue_date: @issue.created_at)
    end
  end

  def issue_params
    params.require(:issue).permit(:title, :body, :teacher_id, :progress, :state, attachments_attributes: [:file])
  end

  def issuable_object
    if params[:project_id]
      Project.find(params[:project_id])
    elsif params[:course_id]
      Course.find(params[:course_id])
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def progress
    [['0%', 0], ['10%', 10], ['20%', 20], ['30%', 30], ['40%', 40], ['50%', 50], ['60%', 60], ['70%', 70], ['80%', 80], ['90%', 90], ['100%', 100]]
  end

  def state
    ['Выполнено', 'В работе', 'Отложено', 'Просрочено']
  end

  def user_issue
    UserAssignment.where(assignmentable_id: @issue.id, assignmentable_type: @issue.class.name).first
  end

end

app/views/issues/_form.html.haml
.col-12
  = form_for [@issuable, @issue], html: { class: "form-horizontal" } do |f|
    - if can? :create, Issue
      .form-group.row
        %label.col-2.col-form-label.text-right Наименование
        .col-10
          = f.text_field :title, placeholder: "Наименование", autofocus: true, class: "form-control"

      .form-group.row
        %label.col-2.col-form-label.text-right Описание
        .col-10
          = f.text_area :body, placeholder: "Описание", class: "form-control", rows: 7

      .form-group.row
        %label.col-2.col-form-label.text-right Прогресс выполнения
        .col-3
          = f.select :progress, {}, {}, { class: "form-control" } do
            - progress.each do |c|
              = content_tag(:option, c.first, value: c.last)
      .form-group.row
        .col-5
          = render 'shared/nested_form/attachments_form', f: f, attachable: @issue

    = f.submit "Сохранить", class: "btn btn-outline-secondary btn-sm"

  - if @issue.persisted? and 1 == 0 # this crap does not work so we decided to turn it off for the presentation
    - if can? :manage, @issue
      = form_for @issue, html: { class: "form-horizontal" } do |f|
        .form-group.row
          %label.col-2.col-form-label.text-right Состояние
          .col-4
            = f.select :state, {}, {}, { class: "form-control" } do
              - state.each do |c|
                = content_tag(:option, c, value: c)
          = f.submit "Сохранить состояние", class: "btn btn-outline-secondary btn-sm"

app/views/issues/_issue.html.haml
.col-12.card
  .row
    .col-12.card-header
      %h5.text-left= issue.title
      .kirill-styles-quick-fix
        = link_to 'Перейти', issue_path(issue), class: "btn btn-outline-secondary btn-sm" if controller_name != 'issues'
        - if can? :manage, issue
          = link_to 'Edit', edit_issue_path(issue), class: "btn btn-outline-secondary btn-sm"
          = link_to 'Settings', issue_user_assignments_path(issue), class: "btn btn-outline-secondary btn-sm"

    .col-12.card-body
      %h4 Прогресс выполнения
      .progress
        .progress-bar.progress-bar-striped.progress-bar-animated{ role: "progressbar",  "aria-valuenow" => "#{issue.progress}", "aria-valuemin" => "0", "aria-valuemax" => "100", style: "width: #{issue.progress}%"}

      %hr
      %h4 Задание
      %hr
      %p= markdown(issue.body)
      - unless issue.attachments.empty?
        %hr
        %p Файлы:
        = render partial: 'shared/nested_form/attachments', locals: { obj: issue }

      .user-answers
        = render issue.user_answers
      .user-answer-create
        - if user_signed_in?
          - if can? :create, UserAnswer
            = form_for [issue, @user_answer], remote: true do |f|
              .form-group.row
                %label.col-2.col-form-label.text-right Новый ответ
                .col-6
                  = f.text_area :body, class: 'form-control'
                .col-2
                  = f.submit 'Сохранить', class: 'btn btn-outline-secondary btn-sm'

app/views/issues/_issue_panel.html.haml
.col-12.card
  .row
    .col-12.card-header
      %h5.text-left Задачи
      .buttons
        %a{ href: issuable_link(issuable), class: "btn btn-sm btn-dark" }
    .col-12.card-body
      .row
        .col-6
          %b Задача
        .col-6
          %b Назначена
      %hr

      - issuable.issues.each do |issue|
        .row
          .col-6
            - if can? :read, issue
              = link_to issue.title, issue_path(issue)
            - else
              %p= issue.title
          .col-6
            - issue.users.each do |user|
              %p= "#{user.f_name} #{user.l_name}"




          -#.col-2
          -#  - if can? :update, issue
          -#    = link_to 'Настроить', issue_user_assignments_path(issue), class: "btn btn-outline-secondary btn-sm"
              -#= link_to 'Редактировать', edit_issue_path(issue), class: "btn btn-outline-secondary btn-sm"
          -#.col-2
          -#  - if can? :update, issue

app/views/issues/_issue_tab.html.haml
- if can? :manage, Issue
  .actions
    = link_to 'Создать задачу', issuable_link(issuable)

.page-content
  .fancy-table-container.issues-table
    %table
      %thead
        %tr
          %th.name Задача
          %th.created-at Назначена
      %tbody
        - issuable.issues.each do |issue|
          %tr
            %th
              - if can? :read, issue
                = link_to issue.title, issue_path(issue)
              - else
                = issue.title
            %td
              - issue.users.each do |user|
                %span= "#{user.f_name} #{user.l_name}"

app/views/issues/edit.html.haml
.errors
  = render 'shared/errors', object: @issue

.col-12.card.bg-light
  .row
    .col-12.card-header
      %a.btn.btn-outline-secondary.btn-sm.back-button{ href: request.referer } Назад
      .row
        .col-12
          %h3 Редактирование задачи

    .col-12.card-body
      = render 'form'

app/views/issues/new.html.haml
.errors
  = render 'shared/errors', object: @issue

.col-12.card.bg-light
  .row
    .col-12.card-header
      %a.btn.btn-outline-secondary.btn-sm.back-button{ href: request.referer } Назад
      .row
        .col-12
          %h3 Создание задачи

    .col-12.card-body
      = render 'form'

app/views/issues/show.html.haml
= render @issue

app/views/issues/user_issues_list.haml
.col-12.card.bg-light
  .row
    .col-12.card-header
      .row
        .col-12
          %h5.text-left Ответы пользователей

    .col-12.card-body
      .row
        .col-3
          %h5 Участник
        .col-3
          %h5 Задача
      - @user_issues.each do |ui|
        .row
          .col-3
            %p= ui.user.f_name
          .col-3
            %p= ui.assignmentable.body