config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :main_fields do

    resources :creation_applications, only: [:new, :create] do
    end

    resources :fields, shallow: true do
      resources :user_assignments, shallow: true

      resources :role_applications, only: [:new, :create] do
      end

      resources :projects, shallow: true do
        resources :wikis, shallow: true

        resources :user_assignments, shallow: true
        resources :issues, shallow: true,except: [:index] do
          get 'user_issues_list', to: 'issues#user_issues_list'
          resources :user_assignments, shallow: true
          resources :user_answers, shallow: true, only: [:create, :update, :destroy]
        end
        resources :role_applications, only: [:new, :create] do
        end
      end
      

      resources :courses, shallow: true do
        resources :wikis, shallow: true
        resources :user_assignments, shallow: true
        resources :issues, shallow: true, except: [:index] do
          resources :user_assignments, shallow: true
          resources :user_answers, shallow: true, only: [:create, :update, :destroy]
        end
        resources :role_applications, only: [:new, :create] do
        end
      end

      resources :creation_applications, only: [:new, :create] do
      
      end
    end
  end

  resources :role_applications, only: [:show, :destroy] do
    patch '/accept', to: 'role_applications#accept', as: :accept
    patch '/reject', to: 'role_applications#reject', as: :reject
  end

  resources :creation_applications, only: [:show, :destroy] do
    patch '/accept', to: 'creation_applications#accept', as: :accept
    patch '/reject', to: 'creation_applications#reject', as: :reject
  end

  patch '/user_answers/:id/accept_user_answer', to: 'user_answers#accept_user_answer'
  patch '/user_answers/:id/reject_user_answer', to: 'user_answers#reject_user_answer'

  get '/notifications', to: 'notifications#index'

  resources :users
  resources :search

  post 'search/projects/', to: 'search#search_projects'

  resources :topics do
    resources :answers, only: [:create, :update, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  get '/notifications', to: 'notifications#index'

###########
  resources :advanced_abilities, only: [:create]
###########

  root to: 'main_fields#index'
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :issue

  has_many :attachments, as: :attachable, dependent: :destroy

  accepts_nested_attributes_for :attachments, reject_if: :all_blank
end

app/controllers/user_answers_controller.rb
class UserAnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_issue, only: [:create]
  before_action :set_user_answer, except: :create

  authorize_resource

  respond_to :js

  def create
    respond_with(@user_answer = current_user.user_answers.create(user_answer_params.merge(recipient_id: @issue.author_id, issue_id: @issue.id, status: "На рассмотрении")))
  end

  def update
    @user_answer.update(user_answer_params)
    respond_with @user_answer, notice: "Ваш ответ успешно изменен!"
  end

  def destroy
    respond_with(@user_answer.destroy)
  end

  def accept_user_answer
    @user_answer.update(status: "Принято")
    redirect_to @user_answer.issue
  end

  def reject_user_answer
    @user_answer.update(status: "Отклонено")
    redirect_to @user_answer.issue
  end


  private

  def set_user_answer
    @user_answer = UserAnswer.find(params[:id])
  end

  def set_issue
    @issue = Issue.find(params[:issue_id])
  end

  def user_answer_params
    params.require(:user_answer).permit(:body, :perfomance, attachments_attributes: [:file])
  end
end

app/helpers/user_answers_helper.rb
module UserAnswersHelper
  def answer_color(user_answer)
    if user_answer.status == "На рассмотрении"
      "<p class='text-secondary'> На рассмотрении </p>".html_safe
    elsif user_answer.status == "Принято"
      "<p class='text-success'> Ответ принят </p>".html_safe
    elsif user_answer.status == "Отклонено"
      "<p class='text-danger'> Ответ отклонен </p>".html_safe
    end
  end


  def user_answer_mark
    [['Балл', 1], ['Балла', 2], ['Балла', 3], ['Балла', 4], ['Баллов', 5], ['Баллов', 6], ['Баллов', 7], ['Баллов', 8], ['Баллов', 9], ['Баллов', 10]]
  end
end

app/views/user_answers/_user_answer.haml
- if user_answer.persisted?
  %div{ class: "user-answer-#{user_answer.id}" }
    .row
      .col-3
        - if user_answer.user.id == user_answer.issue.author_id 
          %p.text-danger= "#{user_answer.user.l_name} #{user_answer.user.l_name}"
        - else 
          %p.text-success= "#{user_answer.user.l_name} #{user_answer.user.l_name}"

        - if user_answer.status == "На рассмотрении" || nil
          - if can? :update, user_answer
            = link_to '+', "/user_answers/#{user_answer.id}/accept_user_answer", method: :patch, class: "btn btn-outline-secondary btn-sm"
            = link_to '-', "/user_answers/#{user_answer.id}/reject_user_answer", method: :patch, class: "btn btn-outline-secondary btn-sm"

      .col-6
        = form_for user_answer, remote: true, html: { id: "edit-user-answer-#{user_answer.id}" } do |f|
          .form-group.row
            .col-3
              %p Оценка
            .col-5
              = f.select :perfomance, {}, {}, { class: "form-control" } do
                - user_answer_mark.each do |m|
                  = content_tag(:option, "#{m.last} #{m.first}", value: m.last)
            .col-4
              = f.submit 'Сохранить', class: 'btn btn-outline-secondary btn-sm'
     
      .col-3
        = answer_color(user_answer)
    %br
    .row
      .col-3.row
        .col-6
          %h5 Балл:
        .col-6
          %h5= user_answer.perfomance
          
      .col-9
        %p= markdown(user_answer.body)
        - unless user_answer.attachments.empty?
          %hr
          %p Файлы:
          = render partial: 'shared/nested_form/attachments', locals: { obj: project }

        - if can?(:update, user_answer)
          = link_to 'Изменить', '', class: 'edit-user-answer-link btn btn-outline-secondary btn-sm', data: { user_answer_id: user_answer.id }
          
          = form_for user_answer, remote: true, html: { id: "edit-user-answer-#{user_answer.id}" } do |f|
            .form-group.row
              .col-8
                = f.text_area :body, rows: 5, class: 'form-control'
              .col-2
                = f.submit 'Сохранить', class: 'btn btn-outline-secondary btn-sm'
          
          = link_to 'Удалить', user_answer_path(user_answer), method: :delete, remote: true, class: 'btn btn-outline-secondary btn-sm'
%hr
%br

app/views/user_answers/create.js.erb
<% if @user_answer.errors.any? %>
  $('.errors').html('<%= j render 'shared/errors', object: @user_answer %>');
<% else %>
  $('.flash').html('<%= j render 'shared/flash' %>');
  $('.user-answers').append('<%= j render @user_answer %>');
  $('.user-answer-create #user_answer_body').val('');
  $('.edit-user-answer-link').click(function(e) {
      e.preventDefault();
      $(this).hide();
      var user_answer_id = $(this).data('userAnswerId');
      $('form#edit-user-answer-' + user_answer_id).show();
});
<% end %>

app/views/user_answers/destroy.js.erb
<% if @user_answer.errors.any? %>
  $('.errors').html('<%= j render 'shared/errors', object: @user_answer %>');
<% else %>
  $('.flash').html('<%= j render 'shared/flash' %>');
  $('.user-answer-' + <%= @user_answer.id %>).remove();
<% end %>

app/views/user_answers/update.js.erb
<% if @user_answer.errors.any? %>
  $('.errors').html('<%= j render 'shared/errors', object: @user_answer %>');
<% else %>
  $('.flash').html('<%= j render 'shared/flash' %>');
  $('.user-answer-' + <%= @user_answer.id %>).html('<%= j render @user_answer %>');
<% end %>