config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :main_fields do

    resources :creation_applications, only: [:new, :create] do
    end

    resources :fields, shallow: true do
      resources :user_assignments, shallow: true

      resources :role_applications, only: [:new, :create] do
      end

      resources :projects, shallow: true do
        resources :wikis, shallow: true

        resources :user_assignments, shallow: true
        resources :issues, shallow: true,except: [:index] do
          get 'user_issues_list', to: 'issues#user_issues_list'
          resources :user_assignments, shallow: true
          resources :user_answers, shallow: true, only: [:create, :update, :destroy]
        end
        resources :role_applications, only: [:new, :create] do
        end
      end
      

      resources :courses, shallow: true do
        resources :wikis, shallow: true
        resources :user_assignments, shallow: true
        resources :issues, shallow: true, except: [:index] do
          resources :user_assignments, shallow: true
          resources :user_answers, shallow: true, only: [:create, :update, :destroy]
        end
        resources :role_applications, only: [:new, :create] do
        end
      end

      resources :creation_applications, only: [:new, :create] do
      
      end
    end
  end

  resources :role_applications, only: [:show, :destroy] do
    patch '/accept', to: 'role_applications#accept', as: :accept
    patch '/reject', to: 'role_applications#reject', as: :reject
  end

  resources :creation_applications, only: [:show, :destroy] do
    patch '/accept', to: 'creation_applications#accept', as: :accept
    patch '/reject', to: 'creation_applications#reject', as: :reject
  end

  patch '/user_answers/:id/accept_user_answer', to: 'user_answers#accept_user_answer'
  patch '/user_answers/:id/reject_user_answer', to: 'user_answers#reject_user_answer'

  get '/notifications', to: 'notifications#index'

  resources :users
  resources :search

  post 'search/projects/', to: 'search#search_projects'

  resources :topics do
    resources :answers, only: [:create, :update, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  get '/notifications', to: 'notifications#index'

###########
  resources :advanced_abilities, only: [:create]
###########

  root to: 'main_fields#index'
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: :author_id
  has_many :answers

  has_many :attachments, as: :attachable, dependent: :destroy

  accepts_nested_attributes_for :attachments, reject_if: :all_blank



  def self.topic_sections
    topics = ["Вопросы администратору", 'Разговоры'] + Field.pluck(:name)
    @topic_sections = []

    for i in 0...topics.count do
      @topic_sections << [i, topics[i]]
    end
    @topic_sections
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  
  authorize_resource

  def index
    respond_with @topics = Topic.all
  end

  def show
    @answer = Answer.new
    respond_with @topic
  end

  def edit; end

  def new
    respond_with @topic = Topic.new
  end

  def create
    respond_with(@topic = Topic.create(topic_params.merge(author_id: current_user.id)))
  end

  def update
    @topic.update(topic_params)
    respond_with @topic
  end

  def destroy
    respond_with @topic.destroy
  end


  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :body, :section, attachments_attributes: [:file])
  end
end

app/views/topics/_form.haml
.col-12
  = form_for @topic, html: {class: "form-horizontal"} do |f|

    .form-group.row
      %label.col-2.col-form-label.text-right Заголовок
      .col-10
        = f.text_field :title, placeholder: "Заголовок", autofocus: true, class: "form-control"

    .form-group.row
      %label.col-2.col-form-label.text-right Описание
      .col-10
        = f.text_area :body, placeholder: "Описание", class: "form-control", rows: 4

    .form-group.row
      %label.col-2.col-form-label.text-right Раздел
      .col-10
        = f.select :section, {}, {}, { class: "form-control" } do
          - Topic.topic_sections.each do |section|
            = content_tag(:option, section[1], value: section[1])

    .form-group.row
      .col-5
        = render 'shared/nested_form/attachments_form', f: f, attachable: @topic

    .row
      .col-12
        = f.submit "Сохранить", class: "btn btn-outline-secondary btn-sm"

        - if @topic.persisted? && can?(:destroy, @topic)
          = link_to "Удалить", topic_path(@topic.id), method: :delete, class: "btn btn-outline-secondary btn-sm", data: { confirm: "Вы уверены?" }

        %a.btn.btn-outline-secondary.btn-sm{ href: request.referer } Назад

app/views/topics/_topic_with_navigation_panel.haml
- content_for :left_panel do
  .border-right
    .nav.flex-column.nav-pills#v-pills-tab{ role: "tablist", "aria-orientation" => "vertical" }
      / %a.nav-link.active.text-dark#v-pills-chavo-tab{ "data-toggle" => "pill", href: "#v-pills-chavo", role: "tab", "aria-controls" => "v-pills-chavo", "aria-selected" => "true" } ЧаВо

      - Topic.topic_sections.each do |t|
        %a.nav-link.text-dark{ id: "v-pills-#{t[0]}-tab", "data-toggle" => "pill", href: "#v-pills-#{t[0]}", role: "tab", "aria-controls" => "v-pills-#{t[0]}", "aria-selected" => "false" }= t[1]

      %br
      %a.nav-link.text-dark.btn.btn-secondary{  href: new_topic_path, role: "tab", "aria-selected" => "false", type: "button" } Новая тема


- content_for :center do
  .tab-content#v-pills-tabContent
    / .tab-pane.fade.show.active#v-pills-chavo{ role: "tabpanel", "aria-labelledby" => "v-pills-chavo-tab" }
    /   .col-12.card
    /     .row
    /       .col-12.card-header
    /         %h5.text-left ЧаВо
    /       .col-12.card-body
    /         %p ЧаВо


    - Topic.topic_sections.each do |section|
      .tab-pane.fade{ id: "v-pills-#{section[0]}", role: "tabpanel", "aria-labelledby" => "v-pills-#{section[0]}-tab" }
        .col-12.card
          .row
            .col-12.card-header
              .row
                .col-12
                  %h5.text-left= section[1]

            .col-12.card-body
              %table.table
                %thead.table-secondary
                  %tr
                    %th{ scope: "col" } Тема
                    %th{ scope: "col" } Автор
                    %th{ scope: "col" } Дата создания
                    %th{ scope: "col" }
                %tbody
                  - Topic.where(section: section[1]).each do |t|
                    %tr
                      %td= t.title
                      %td= "#{t.author.l_name} #{t.author.f_name}"
                      %td= t.created_at.strftime("%d.%m.%Y %H:%M")
                      %td
                        = link_to 'Перейти', topic_path(t.id), class: 'btn btn-outline-secondary btn-sm'

app/views/topics/edit.haml
.errors
  = render 'shared/errors', object: @topic

.col-12.card.bg-light
  .row
    .col-12.card-header
      .row
        .col-12
          %h3 Редактирование темы

    .col-12.card-body
      = render 'form'

app/views/topics/index.haml
= render 'topic_with_navigation_panel'

app/views/topics/new.haml
.errors
  = render 'shared/errors', object: @topic

.col-12.card.bg-light
  .row
    .col-12.card-header
      .row
        .col-12
          %h3 Новая тема

    .col-12.card-body
      = render 'form'

app/views/topics/show.haml
.col-12.card
  .row
    .col-12.card-header
      .row
        .col-10
          %h5.text-left= @topic.title
        .col-2
          - if can? :update, @topic
            = link_to "Изменить", edit_topic_path(@topic), class: 'btn btn-sm btn-dark'

    .col-12.card-body
      .col-12
        %p= markdown(@topic.body)
        - unless @topic.attachments.empty?
          %hr
          %p Файлы:
          = render partial: 'shared/nested_form/attachments', locals: { obj: @topic }
        %hr

      .answers.col-12
        - @topic.answers.each do |answer|
          %div{ class: "answer-#{answer.id} card col-12 bg-light" }
            = render answer
          %br
        %div{ class: "new-answer card col-12 bg-light" }

      %br
      .answer-create.col-12
        - if user_signed_in?
          = form_for [@topic, @answer], remote: true do |f|
            .form-group.row
              .col-2
                = f.label :body, 'Новый ответ'
              .col-8
                = f.text_area :body, class: 'form-control'
              .col-2
                = f.submit 'Сохранить', class: 'btn btn-outline-secondary btn-sm'


              / %
            / %p Attachments:

            / #attachments
            /   = f.fields_for :attachments do |attachment|
            /     = render 'shared/attachments', f: attachment
            /   .links
            /     = link_to_add_association 'add file', f, :attachments, partial: 'shared/attachments'