config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :main_fields do

    resources :creation_applications, only: [:new, :create] do
    end

    resources :fields, shallow: true do
      resources :user_assignments, shallow: true

      resources :role_applications, only: [:new, :create] do
      end

      resources :projects, shallow: true do
        resources :wikis, shallow: true

        resources :user_assignments, shallow: true
        resources :issues, shallow: true,except: [:index] do
          get 'user_issues_list', to: 'issues#user_issues_list'
          resources :user_assignments, shallow: true
          resources :user_answers, shallow: true, only: [:create, :update, :destroy]
        end
        resources :role_applications, only: [:new, :create] do
        end
      end
      

      resources :courses, shallow: true do
        resources :wikis, shallow: true
        resources :user_assignments, shallow: true
        resources :issues, shallow: true, except: [:index] do
          resources :user_assignments, shallow: true
          resources :user_answers, shallow: true, only: [:create, :update, :destroy]
        end
        resources :role_applications, only: [:new, :create] do
        end
      end

      resources :creation_applications, only: [:new, :create] do
      
      end
    end
  end

  resources :role_applications, only: [:show, :destroy] do
    patch '/accept', to: 'role_applications#accept', as: :accept
    patch '/reject', to: 'role_applications#reject', as: :reject
  end

  resources :creation_applications, only: [:show, :destroy] do
    patch '/accept', to: 'creation_applications#accept', as: :accept
    patch '/reject', to: 'creation_applications#reject', as: :reject
  end

  patch '/user_answers/:id/accept_user_answer', to: 'user_answers#accept_user_answer'
  patch '/user_answers/:id/reject_user_answer', to: 'user_answers#reject_user_answer'

  get '/notifications', to: 'notifications#index'

  resources :users
  resources :search

  post 'search/projects/', to: 'search#search_projects'

  resources :topics do
    resources :answers, only: [:create, :update, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  get '/notifications', to: 'notifications#index'

###########
  resources :advanced_abilities, only: [:create]
###########

  root to: 'main_fields#index'
end

app/models/field.rb
class Field < ApplicationRecord
  belongs_to :main_field

  has_many :user_assignments, as: :assignmentable

  has_many :projects
  has_many :courses
  has_many :wikis
  has_many :users, through: :user_assignments

  has_many :user_applications, as: :application_receiver

  has_many :creation_applications, as: :creation_applicable
  has_many :role_applications, as: :role_applicable


  validates :name, :short_description, :description, presence: true
  # belongs_to :curator, class_name: 'User', foreign_key: 'curator_id'


end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]
  before_action :set_main_field, only: [:new, :create, :index]

  authorize_resource

  def index
    respond_with @fields = @main_field.fields
  end

  def show
    respond_with @field
  end

  def edit; end

  def new
    respond_with @field = @main_field.fields.new
  end

  def create
    respond_with(@field = @main_field.fields.create(field_params))
  end

  def update
    @field.update(field_params)
    respond_with @field
  end

  def destroy
    main_field = @field.main_field
    @field.destroy
    redirect_to main_field
  end


  private

  def set_field
    @field = Field.find(params[:id])
  end

  def set_main_field
    @main_field = MainField.find(params[:main_field_id])
  end

  def field_params
    params.require(:field).permit(:name, :short_description, :description, :curator_id)
  end
end

app/helpers/fields_helper.rb
module FieldsHelper
    def admin_role_applications
        RoleApplication.all.select { |application| application.required_reviewer_role == Role.by_name('admin')}
    end

    def admin_creation_applications
        CreationApplication.all.select { |application| application.required_reviewer_role == Role.by_name('admin')}
    end

    def field_creation_applications
        CreationApplication.all.select { |application| application.creation_applicable == @field && application.required_reviewer_role.name == 'curator'}
    end
  end
  

app/views/fields/_courses_tab.html.haml
- if can? :manage, @field
  .actions
    = link_to 'Добавить учебный материал', new_field_course_path(@field)
    
= render 'courses/courses_list', courses: @field.courses

app/views/fields/_field_with_navigation_panel.html.haml
- content_for :left_panel do
  .border-right
    .nav.flex-column.nav-pills#v-pills-tab{role: "tablist", "aria-orientation" => "vertical"}
      %a.nav-link.active.text-dark#v-pills-home-tab{ "data-toggle" => "pill", href: "#v-pills-home", role: "tab", "aria-controls" => "v-pills-home", "aria-selected" => "true" } Описание
      %a.nav-link.text-dark#v-pills-course-tab{ "data-toggle" => "pill", href: "#v-pills-course", role: "tab", "aria-controls" => "v-pills-course", "aria-selected" => "false" } Учебные материалы
      %a.nav-link.text-dark#v-pills-project-tab{ "data-toggle" => "pill", href: "#v-pills-project", role: "tab", "aria-controls" => "v-pills-project", "aria-selected" => "false" } Проекты

- content_for :center do
  .tab-content#v-pills-tabContent

    .tab-pane.fade.show.active#v-pills-home{ role: "tabpanel", "aria-labelledby" => "v-pills-home-tab" }
      .col-12.card
        .row
          .col-12.card-header
            %h5.text-left= @field.name
          .col-12.card-body
            %p= markdown(@field.description)
            - if can? :update, @field
              = link_to 'Редактировать', edit_field_path(@field), class: "btn btn-outline-secondary btn-sm"
              = link_to 'Настроить', field_user_assignments_path(@field), class: "btn btn-outline-secondary btn-sm"


    .tab-pane.fade#v-pills-course{ role: "tabpanel", "aria-labelledby" => "v-pills-course-tab" }
      .col-12.card
        .row
          .col-12.card-body
            .row
              .col-12.card-header
                %h5.text-left Учебные материалы
                .buttons
                  - if can? :manage, @field
                    = link_to "Добавить", new_field_course_path(@field), class: 'btn btn-sm btn-dark'

              .col-12.card-body
                .row
                  - @field.courses.each do |course|
                    .col-6
                      = render course


    .tab-pane.fade#v-pills-project{ role: "tabpanel", "aria-labelledby" => "v-pills-project-tab" }
      .col-12.card
        .row
          .col-12.card-body
            .row
              .col-12.card-header
                %h5.text-left Проекты
                .butons
                  - if can? :manage, @field
                    = link_to "Добавить", new_field_project_path(@field), class: 'btn btn-sm btn-dark'

          .col-12.card-body
            .row
              - @field.projects.each do |project|
                .col-6
                  = render project

app/views/fields/_field_with_tabs.html.haml
- content_for :main_container do
  %header.page-header
    %h1.page-title
      = @field.name
    .actions
      - if can? :manage, Field
        %a{href: edit_field_path(@field)}
          %img.settings{src: image_path('settings.svg'), alt: 'Редактировать направление'}

  %nav.page-nav
    #nav-tab.nav.page-tabs{:role => "tablist"}
      %a#nav-home-tab.tab.active{"aria-controls" => "nav-description", "aria-selected" => "true", "data-toggle" => "tab", :href => "#nav-description", :role => "tab"} Описание направления
      %a#nav-members-tab.tab{"aria-controls" => "nav-members", "aria-selected" => "false", "data-toggle" => "tab", :href => "#nav-members", :role => "tab"} Руководители
      %a#nav-materials-tab.tab{"aria-controls" => "nav-materials", "aria-selected" => "false", "data-toggle" => "tab", :href => "#nav-materials", :role => "tab"} Курсы
      %a#nav-projects-tab.tab{"aria-controls" => "nav-projects", "aria-selected" => "false", "data-toggle" => "tab", :href => "#nav-projects", :role => "tab"} Проекты
      %a#nav-role-applications-tab.tab{"aria-controls" => "nav-role-applications", "aria-selected" => "false", "data-toggle" => "tab", :href => "#nav-role-applications", :role => "tab"} Заявки на роли
      %a#nav-creation-applications-tab.tab{"aria-controls" => "nav-creation-applications", "aria-selected" => "false", "data-toggle" => "tab", :href => "#nav-creation-applications", :role => "tab"} Заявки на создание

  .page-content
    #nav-tabContent.tab-content
      #nav-description.tab-pane.fade.show.active.tab-content{"aria-labelledby" => "nav-home-tab", :role => "tabpanel"}
        .actions
          = link_to 'Подать заявку на создание', new_field_creation_application_path(@field)
          - if RoleApplication.can_be_sent(current_user, @field)
            = link_to 'Подать заявку на роль', new_field_role_application_path(@field)
        = markdown @field.description
      #nav-members.tab-pane.fade.tab-content{"aria-labelledby" => "nav-members-tab", :role => "tabpanel"}
        = render 'users/users_tab', issuable: @field
      #nav-materials.tab-pane.fade.tab-content{"aria-labelledby" => "nav-materials-tab", :role => "tabpanel"}
        = render 'courses_tab'
      #nav-projects.tab-pane.fade.tab-content{"aria-labelledby" => "nav-projects-tab", :role => "tabpanel"}
        = render 'projects_tab'
      #nav-role-applications.tab-pane.fade.tab-content{"aria-labelledby" => "nav-role-applications-tab", :role => "tabpanel"}
        = render 'role_applications/role_applications_tab', role_applications: @field.role_applications
      #nav-creation-applications.tab-pane.fade.tab-content{"aria-labelledby" => "nav-creation-applications-tab", :role => "tabpanel"}
        = render 'creation_applications/creation_applications_tab', creation_applications: field_creation_applications

app/views/fields/_fields_list.html.haml
.cards
  - fields.each do |field|
    .card.li-card
      .card-body
        %h5.card-title
          = field.name
        %p.card-text
          = field.short_description
        - if can? :read, field
          = link_to 'Просмотр', field_path(field), class: "btn btn-outline-secondary btn-sm"

app/views/fields/_form.html.haml
.col-12
  = form_for @field, html: {class: "form-horizontal"} do |f|

    .form-group.row
      %label.col-2.col-form-label.text-right Наименование
      .col-10
        = f.text_field :name, placeholder: "Наименование", autofocus: true, class: "form-control", required: ''

    .form-group.row
      %label.col-2.col-form-label.text-right Краткое описание
      .col-10
        = f.text_area :short_description, placeholder: "Краткое описание", class: "form-control", rows: 2, required: ''

    .form-group.row
      %label.col-2.col-form-label.text-right Описание
      .col-10
        = f.text_area :description, placeholder: "Описание", class: "form-control", rows: 7, required: ''

    .row
      .col-6
      .col-6
        = f.submit "Сохранить", class: "btn btn-outline-secondary btn-sm"

        - if @field.persisted? && can?(:manage, Field)
          = link_to "Удалить", field_path(@field.id), method: :delete, class: "btn btn-outline-secondary btn-sm", data: { confirm: "Вы уверены?" }

        %a.btn.btn-outline-secondary.btn-sm{ href: request.referer } Назад

app/views/fields/_projects_tab.html.haml
- if can? :manage, @field
  .actions
    = link_to 'Добавить проект', new_field_project_path(@field)

= render 'projects/projects_table', projects: @field.projects

app/views/fields/edit.html.haml
.errors
  = render 'shared/errors', object: @field

.col-12.card.bg-light
  .row
    .col-12.card-header
      .row
        .col-12
          %h3 Редактирование направления

    .col-12.card-body
      = render 'form'

app/views/fields/index.html.haml
- content_for :main_container do
  %header.page-header
    %h1.page-title
      Субнаправления
    .actions
      - if can? :manage, Field
        %a{href: new_main_field_field_path}
          %img{src: image_path('add.svg'), alt: 'Добавить направление'}

  %nav.page-nav
    #nav-tab.nav.page-tabs{:role => "tablist"}
      %a#nav-home-tab.tab.active{"aria-controls" => "nav-home", "aria-selected" => "true", "data-toggle" => "tab", :href => "#nav-home", :role => "tab"} Список
      %a#nav-role-applications-tab.tab{"aria-controls" => "nav-role-applications", "aria-selected" => "false", "data-toggle" => "tab", :href => "#nav-role-applications", :role => "tab"} Заявки на роли
      %a#nav-creation-applications-tab.tab{"aria-controls" => "nav-creation-applications", "aria-selected" => "false", "data-toggle" => "tab", :href => "#nav-creation-applications", :role => "tab"} Заявки на создание

  .page-content
    #nav-tabContent.tab-content
      #nav-home.tab-pane.fade.show.active.tab-content{"aria-labelledby" => "nav-home-tab", :role => "tabpanel"}
        = render 'fields/fields_list', fields: @fields
      #nav-role-applications.tab-pane.fade.tab-content{"aria-labelledby" => "nav-role-applications-tab", :role => "tabpanel"}
        = render 'role_applications/role_applications_tab', role_applications: admin_role_applications
      #nav-creation-applications.tab-pane.fade.tab-content{"aria-labelledby" => "nav-creation-applications-tab", :role => "tabpanel"}
        = render 'creation_applications/creation_applications_tab', creation_applications: admin_creation_applications
    

app/views/fields/new.html.haml
.col-12.card.bg-light
  .row
    .col-12.card-header
      .row
        .col-12
          %h3 Создание направления

    .col-12.card-body
      = render 'form'

app/views/fields/show.html.haml
= render 'field_with_tabs'